### ISSUE TITLE
Magphase vocoder 

### ISSUE THREAD

**Issue by Aliraheem** [CSTR-Edinburgh/magphase#15]
I am trying to work with Magphase in the 3.6 python environment. After some modifying in Magphase files to work with my python version, I still have some problems: 

@6985130d66b7:~/magphase/demos$ python demo_copy_synthesis_low_dim.py
Analysing.....................................................
Extracting epochs with REAPER...
Residual symmetry: P:2120.314453  N:1149.693604  MEAN:0.606241
Inverting signal
Synthesising.................................................
Traceback (most recent call last):
  File "demo_copy_synthesis_low_dim.py", line 79, in <module>
    v_syn_sig = mp.synthesis_from_compressed(m_mag_mel_log, m_real_mel, m_imag_mel, v_lf0_smth, fs, b_const_rate=b_const_rate, b_out_hpf=False)
  File "/magphase/src/magphase.py", line 854, in synthesis_from_compressed
    m_mag = np.exp(la.sp_mel_unwarp(m_mag_mel_log, fft_len_half, alpha=alpha, in_type='log'))
  File "/magphase/src/libaudio.py", line 683, in sp_mel_unwarp
    m_sp_unwr = mcep_to_sp_cosmat(m_mcep[:,:ncoeffs], nbins_out, alpha=alpha, out_type=in_type)
  File "/magphase/src/libaudio.py", line 611, in mcep_to_sp_cosmat
    v_bins_out  = np.linspace(0, np.pi, num=n_spbins)
  File "<__array_function__ internals>", line 6, in linspace
  File "/.local/lib/python3.6/site-packages/numpy/core/function_base.py", line 113, in linspace
    num = operator.index(num)
TypeError: 'float' object cannot be interpreted as an integer

**Comment by felipeespic** [comment]
Hi, probably if you change `v_bins_out = np.linspace(0, np.pi, num=n_spbins)` (in line 611, in /magphase/src/libaudio.py) by `v_bins_out = np.linspace(0, np.pi, num=int(n_spbins))` will solve the problem.

**Comment by Aliraheem** [comment]
thanks it works
