### ISSUE TITLE
run 0_batch_feature_extraction_for_merlin.py error

### ISSUE THREAD

**Issue by KnowBetterHelps** [CSTR-Edinburgh/magphase#4]
when I run 0_batch_feature_extraction_for_merlin.py ，I get the following error：

Analysing file: 108955.wav............................
Extracting epochs with REAPER...
Residual symmetry: P:934.997803  N:1402.585083  MEAN:-0.363143
Traceback (most recent call last):
  File "0_batch_feature_extraction_for_merlin.py", line 63, in <module>
    feat_extraction(in_wav_dir, file_name_token, out_feats_dir)
  File "0_batch_feature_extraction_for_merlin.py", line 40, in feat_extraction
    mp.analysis_compressed(wav_file, out_dir=out_feats_dir)
  File "/mnt/diskd/deng/training-tts-magphase/src/magphase.py", line 1585, in analysis_compressed
    m_mag, m_real, m_imag, v_f0, fs, v_shift = analysis_lossless(wav_file, fft_len=fft_len)
  File "/mnt/diskd/deng/training-tts-magphase/src/magphase.py", line 1565, in analysis_lossless
    m_fft, v_shift = analysis_with_del_comp_from_pm(v_sig, fs, v_pm_smpls, fft_len=fft_len)
  File "/mnt/diskd/deng/training-tts-magphase/src/magphase.py", line 196, in analysis_with_del_comp_from_pm
    raise ValueError("fft_len (%d) is shorter than the maximum frame length (%d). Please, increase de FFT length." % (fft_len,len_max))
ValueError: fft_len (4096) is shorter than the maximum frame length (14972). Please, increase de FFT length.

Can someone give me a hand?

**Comment by felipeespic** [comment]
Hi, the reason that causes this problem is that the longest frame extracted from your data is longer than the specified FFT length.  

Could you send me the wavefile, so I can implement a solution, please?

In the meantime, could you try by increasing the FFT length by let's say 16384? I know it is suboptimal, but it is just to check if that works.

**Comment by felipeespic** [comment]
I just fixed it in the commit e3d20fa50ce59adec7c0aa64324665a964da6799. Please, could you check if it works OK now, please?

Thanks!

**Comment by KnowBetterHelps** [comment]
many thanks, It's all right now!!
